### ISSUE TITLE
推送消息失败

### ISSUE THREAD

**Issue by fainle** [PPMESSAGE/ppmessage-lite-server#1]
[E 170307 14:21:08 web:1548] Uncaught exception GET /pcsocket/WS (127.0.0.1)
    HTTPServerRequest(protocol='http', host='127.0.0.1:8945', method='GET', uri='/pcsocket/WS', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Origin': 'http://127.0.0.1:8945', 'Upgrade': 'websocket', 'Sec-Websocket-Extensions': 'x-webkit-deflate-frame', 'Sec-Websocket-Version': '13', 'Connection': 'Upgrade', 'Sec-Websocket-Key': 'aGsX0NY6FJyh81UYF6XTgQ==', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/602.4.8 (KHTML, like Gecko) Version/10.0.3 Safari/602.4.8', 'Host': '127.0.0.1:8945', 'Pragma': 'no-cache', 'Cache-Control': 'no-cache'})
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/site-packages/tornado/web.py", line 1425, in _stack_context_handle_exception
        raise_exc_info((type, value, traceback))
      File "/usr/local/lib/python2.7/site-packages/tornado/stack_context.py", line 314, in wrapped
        ret = fn(*args, **kwargs)
      File "/usr/local/lib/python2.7/site-packages/tornado/websocket.py", line 364, in on_connection_close
        self.on_close()
      File "/data/htdocs/python/ppmessage-lite-server/ppmessage/pcsocket/wshandler.py", line 223, in on_close
        self.delegate.unmap_device(self.device_uuid)
    AttributeError: PCSocketDelegate instance has no attribute 'unmap_device'

[I 170307 14:21:08 wshandler:184] WS MESSAGE..... {"type":"auth","api_token":"OGQ2OTVlMGIyNzQ1NjYwMjA0MTM4NjZjOTViY2I3Zjg2ZDExMWU0ZA==","app_uuid":"7e60614a-02fd-11e7-bf66-3c15c2e66564","user_uuid":"16768a68-02fe-11e7-a63c-3c15c2e66564","device_uuid":"168201f3-02fe-11e7-bbca-3c15c2e66564","extra_data":{"page_title":"PPMessage Lite Test Team","page_url":"http://127.0.0.1:8945/ppcom/enterprise/eyJ1dWlkIjoiN2U2MDYxNGEtMDJmZC0xMWU3LWJmNjYtM2MxNWMyZTY2NTY0IiwiYXBwX25hbWUiOiJQUE1lc3NhZ2UlMjBMaXRlJTIwVGVzdCUyMFRlYW0ifQ==","browser_os":"Mac OS X","browser_os_version":"10_12_3","browser_name":"Safari","browser_version":"10.0.3","browser_language":"zh-cn","language_override":"zh-cn","document_referrer":""},"is_sider_device":false,"is_mobile_device":false,"is_service_user":false}
[E 170307 14:21:08 websocket:415] Uncaught exception in /pcsocket/WS
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/site-packages/tornado/websocket.py", line 412, in _run_callback
        callback(*args, **kwargs)
      File "/data/htdocs/python/ppmessage-lite-server/ppmessage/pcsocket/wshandler.py", line 211, in on_message
        _f(_body)
      File "/data/htdocs/python/ppmessage-lite-server/ppmessage/pcsocket/wshandler.py", line 92, in _on_auth
        self.delegate.map_device(self.device_uuid)
    AttributeError: PCSocketDelegate instance has no attribute 'map_device'

**Comment by dingguijin** [comment]
Thanks for your issue.

FIXED.
